exports.student = {
  _id: { $oid: "68ddeea9c69c82f2a0226c94" },
  name: "Tathagata Mishra",
  email: "tathagatamishra007@gmail.com",
  mobile: "7602728880",
  userName: "tathagatamishra",
  presentKyu: "1th Kyu - Brown Belt",
  lastCertificateNum: "",
  profileImage: "https://cdn-icons-png.flaticon.com/512/5046/5046943.png",
  instructorName: "Sabyasachi Giri",
  dojoName: "Shubukan Dojo",
  instructorId: "68dfc2a8f826b400e4f4bba4",
  isVerified: true,
  isDeleted: false,
  createdAt: { $date: "2025-10-02T03:16:57.423Z" },
  updatedAt: { $date: "2026-01-11T15:21:46.085Z" },
  __v: 0,
  instructorIdentity: "Shubukan India Head",
};

exports.instructor = {
  _id: { $oid: "68dfc2a8f826b400e4f4bba4" },
  name: "Sabyasachi Giri",
  userName: "sabyasachi",
  email: "androidsabya@gmail.com",
  mobile: "9851852499",
  instructorId: "657WZOWVT0",
  profileImage: "",
  isVerified: true,
  isDeleted: false,
  createdAt: { $date: "2025-10-03T12:33:44.074Z" },
  updatedAt: { $date: "2026-01-11T16:11:55.840Z" },
  __v: 0,
};

exports.mockQuestions = [
  {
    id: "q1",
    questionText: 'What is the literal translation of "Karate"?',
    options: ["Empty Hand", "Hard Fist", "Way of Peace", "Iron Body"],
    correctAnswer: 0,
  },
  {
    id: "q2",
    questionText: "Which country is considered the birthplace of Karate?",
    options: ["Japan", "China", "Okinawa", "Korea"],
    correctAnswer: 2,
  },
  {
    id: "q3",
    questionText: 'What does "Dojo" mean?',
    options: [
      "Fighting Arena",
      "Place of the Way",
      "Training Hall",
      "Meditation Room",
    ],
    correctAnswer: 1,
  },
  {
    id: "q4",
    questionText: "What is the bow called in Japanese martial arts?",
    options: ["Hajime", "Rei", "Yame", "Kamae"],
    correctAnswer: 1,
  },
  {
    id: "q5",
    questionText: "Which kata is typically taught first to beginners?",
    options: ["Heian Shodan", "Bassai Dai", "Kanku Dai", "Empi"],
    correctAnswer: 0,
  },
  {
    id: "q6",
    questionText: 'What does "Kiai" represent?',
    options: ["Silence", "Spirit Shout", "Meditation", "Stance"],
    correctAnswer: 1,
  },
  {
    id: "q7",
    questionText: 'What is "Kumite"?',
    options: ["Solo practice", "Sparring", "Meditation", "Belt tying"],
    correctAnswer: 1,
  },
  {
    id: "q8",
    questionText: 'What does "Sensei" mean?',
    options: ["Student", "Teacher", "Master", "Friend"],
    correctAnswer: 1,
  },
  {
    id: "q9",
    questionText: 'What is the proper response to "Sensei ni rei"?',
    options: ["Hai!", "Osu!", "Bow to the teacher", "Stand at attention"],
    correctAnswer: 2,
  },
  {
    id: "q10",
    questionText: 'What is "Zuki"?',
    options: ["Kick", "Block", "Punch", "Stance"],
    correctAnswer: 2,
  },
  {
    id: "q11",
    questionText: "Which stance is the front stance called?",
    options: [
      "Kokutsu Dachi",
      "Zenkutsu Dachi",
      "Kiba Dachi",
      "Neko Ashi Dachi",
    ],
    correctAnswer: 1,
  },
  {
    id: "q12",
    questionText: 'What does "Mawashi Geri" mean?',
    options: ["Front Kick", "Side Kick", "Roundhouse Kick", "Back Kick"],
    correctAnswer: 2,
  },
  {
    id: "q13",
    questionText: 'What is the purpose of "Kata"?',
    options: [
      "Strength training",
      "Formal exercises",
      "Competition only",
      "Stretching",
    ],
    correctAnswer: 1,
  },
  {
    id: "q14",
    questionText: 'What does "Yame" command mean?',
    options: ["Begin", "Stop", "Continue", "Ready"],
    correctAnswer: 1,
  },
  {
    id: "q15",
    questionText: 'What is "Oi Zuki"?',
    options: ["Reverse Punch", "Lunge Punch", "Jab", "Hook Punch"],
    correctAnswer: 1,
  },
  {
    id: "q16",
    questionText: "How many Heian katas are there?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
  },
  {
    id: "q17",
    questionText: 'What is "Gedan Barai"?',
    options: ["High Block", "Middle Block", "Low Block", "Knife Hand Block"],
    correctAnswer: 2,
  },
  {
    id: "q18",
    questionText: 'What does "Hajime" mean?',
    options: ["Stop", "Begin", "Ready", "Bow"],
    correctAnswer: 1,
  },
  {
    id: "q19",
    questionText: "What is the traditional karate uniform called?",
    options: ["Hakama", "Gi", "Kimono", "Judogi"],
    correctAnswer: 1,
  },
  {
    id: "q20",
    questionText: 'What does "Shotokan" refer to?',
    options: [
      "A technique",
      "A style of Karate",
      "A training method",
      "A weapon",
    ],
    correctAnswer: 1,
  },
  {
    id: "q21",
    questionText: 'What is "Kihon"?',
    options: [
      "Free sparring",
      "Basic techniques",
      "Advanced kata",
      "Competition rules",
    ],
    correctAnswer: 1,
  },
  {
    id: "q22",
    questionText: 'What does "Seiza" mean?',
    options: [
      "Standing position",
      "Fighting stance",
      "Formal sitting",
      "Meditation pose",
    ],
    correctAnswer: 2,
  },
  {
    id: "q23",
    questionText: 'What is "Mae Geri"?',
    options: ["Front Kick", "Side Kick", "Back Kick", "Hook Kick"],
    correctAnswer: 0,
  },
  {
    id: "q24",
    questionText: 'What does "Mokuso" command indicate?',
    options: ["Begin training", "Meditation/Close eyes", "Bow", "Line up"],
    correctAnswer: 1,
  },
  {
    id: "q25",
    questionText: 'What is "Gyaku Zuki"?',
    options: ["Lunge Punch", "Reverse Punch", "Jab", "Upper Cut"],
    correctAnswer: 1,
  },
  {
    id: "q26",
    questionText: 'What does "Kyu" represent?',
    options: [
      "Black belt rank",
      "Colored belt rank",
      "Technique level",
      "Age group",
    ],
    correctAnswer: 1,
  },
  {
    id: "q27",
    questionText: 'What is the meaning of "Domo Arigato Gozaimashita"?',
    options: [
      "Good morning",
      "Thank you very much",
      "Please teach me",
      "Goodbye",
    ],
    correctAnswer: 1,
  },
  {
    id: "q28",
    questionText: 'What is "Age Uke"?',
    options: ["Rising Block", "Middle Block", "Low Block", "Inside Block"],
    correctAnswer: 0,
  },
  {
    id: "q29",
    questionText: 'What does "Dan" signify?',
    options: [
      "Beginner level",
      "Black belt level",
      "Competition rank",
      "Teaching certificate",
    ],
    correctAnswer: 1,
  },
  {
    id: "q30",
    questionText:
      "What is the first principle of Karate according to Master Funakoshi?",
    options: [
      "Train hard",
      "Karate begins and ends with respect",
      "Never give up",
      "Practice makes perfect",
    ],
    correctAnswer: 1,
  },
];

exports.mockExams = [
  {
    id: "exam1",
    examSet: "Basic Karate Knowledge - Set A",
    examDuration: 30,
    totalQuestionCount: 30,
    eachQuestionMarks: 1,
    kyu: "10th Kyu",
    questions: this.mockQuestions,
    isPublic: true,
    examType: "online",
    status: "upcoming",
    examDate: new Date("2026-03-05"),
  },
  {
    id: "exam2",
    examSet: "Intermediate Karate - Set B",
    examDuration: 45,
    totalQuestionCount: 30,
    eachQuestionMarks: 2,
    kyu: "6th Kyu",
    questions: this.mockQuestions.slice(0, 20),
    isPublic: true,
    examType: "online",
    status: "ongoing",
    examDate: new Date("2026-02-26"),
  },
  {
    id: "exam3",
    examSet: "Kyu Belt Gradation Exam",
    examDuration: 120,
    totalQuestionCount: 364,
    eachQuestionMarks: 1,
    kyu: "9th Kyu",
    questions: [],
    isPublic: false,
    examType: "offline",
    status: "upcoming",
    examDate: new Date("2026-03-10"),
    venue: "Shubukan India Dojo, Mumbai",
  },
  {
    id: "exam4",
    examSet: "Advanced Belt Gradation",
    examDuration: 120,
    totalQuestionCount: 364,
    eachQuestionMarks: 1,
    kyu: "5th Kyu",
    questions: [],
    isPublic: false,
    examType: "offline",
    status: "ongoing",
    examDate: new Date("2026-02-26"),
    venue: "Shubukan India Dojo, Delhi",
  },
  {
    id: "exam5",
    examSet: "Previous Online Assessment",
    examDuration: 30,
    totalQuestionCount: 30,
    eachQuestionMarks: 1,
    kyu: "8th Kyu",
    questions: this.mockQuestions,
    isPublic: true,
    examType: "online",
    status: "completed",
    examDate: new Date("2026-02-15"),
  },
  {
    id: "exam6",
    examSet: "Previous Offline Gradation",
    examDuration: 120,
    totalQuestionCount: 364,
    eachQuestionMarks: 1,
    kyu: "7th Kyu",
    questions: [],
    isPublic: false,
    examType: "offline",
    status: "completed",
    examDate: new Date("2026-02-10"),
    venue: "Shubukan India Dojo, Bangalore",
  },
];

// Mock Exam Attempts
exports.mockExamAttempts = [
  {
    examId: "exam1",
    studentId: "s1",
    answers: {},
    marksObtained: 24,
    totalMarks: 30,
    correctCount: 24,
    wrongCount: 6,
    submittedAt: new Date("2026-02-15"),
  },
  {
    examId: "exam2",
    studentId: "s1",
    answers: {},
    marksObtained: 32,
    totalMarks: 40,
    correctCount: 16,
    wrongCount: 4,
    submittedAt: new Date("2026-02-18"),
  },
];

// Mock Kata Images
exports.mockKataImages = [
  {
    id: "k1",
    studentId: "s1",
    imageUrl: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400",
    caption: "Heian Shodan - Front Stance",
    uploadedAt: new Date("2026-02-20"),
  },
  {
    id: "k2",
    studentId: "s1",
    imageUrl: "https://images.unsplash.com/photo-1563199930-77cda46a6c4e?w=400",
    caption: "Mae Geri Practice",
    uploadedAt: new Date("2026-02-21"),
  },
];
